const ActionTypes = {
	INITIALIZATION : "INITIALIZATION",
  ADD_NOTIFICATIONLINK : 'ADD_NOTIFICATIONLINK',
  ADD_DEEPLINK : 'ADD_DEEPLINK',
  SHOW_LOADER : 'SHOW_LOADER'
};

export default ActionTypes;
